#  Unequal Split Without Error

In [2]:
import numpy as np

arr = np.arange(1, 21)

parts = np.array_split(arr, 6)

for i, p in enumerate(parts):
    print(f"Part {i+1}: {p}, Length: {len(p)}")

Part 1: [1 2 3 4], Length: 4
Part 2: [5 6 7 8], Length: 4
Part 3: [ 9 10 11], Length: 3
Part 4: [12 13 14], Length: 3
Part 5: [15 16 17], Length: 3
Part 6: [18 19 20], Length: 3


# Dynamic Split

In [3]:
arr = np.array([5,10,15,20,25,30,35,40])

n = 3
parts = np.array_split(arr, n)

for p in parts:
    print(p)

[ 5 10 15]
[20 25 30]
[35 40]


# Even & Odd Index Split

In [4]:
arr = np.arange(10)

even = arr[::2]
odd = arr[1::2]

print("Even index:", even)
print("Odd index:", odd)

Even index: [0 2 4 6 8]
Odd index: [1 3 5 7 9]


# Diagonal vs Non-Diagonal

In [5]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

diag = np.diag(arr)

non_diag = arr[~np.eye(3, dtype=bool)]

print("Diagonal:", diag)
print("Non-diagonal:", non_diag)

Diagonal: [1 5 9]
Non-diagonal: [2 3 4 6 7 8]


#  Multi-Axis Split

In [6]:
arr = np.arange(1, 25).reshape(4,6)

row_split = np.array_split(arr, 2, axis=0)

for part in row_split:
    col_split = np.array_split(part, 3, axis=1)
    for c in col_split:
        print(c)

[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]
[[13 14]
 [19 20]]
[[15 16]
 [21 22]]
[[17 18]
 [23 24]]


# Even & Odd Values Split

In [7]:
arr = np.array([2,4,6,7,9,12,14,17,20])

even = arr[arr % 2 == 0]
odd = arr[arr % 2 != 0]

print("Even:", even)
print("Odd:", odd)

Even: [ 2  4  6 12 14 20]
Odd: [ 7  9 17]


#  Split + Reverse

In [8]:
arr = np.arange(1, 13)

parts = np.array_split(arr, 4)

for p in parts:
    print(p[::-1])

[3 2 1]
[6 5 4]
[9 8 7]
[12 11 10]


# Threshold Split

In [9]:
arr = np.array([10,22,5,18,30,3,25])

low = arr[arr <= 15]
high = arr[arr > 15]

print("<=15:", low)
print(">15:", high)

<=15: [10  5  3]
>15: [22 18 30 25]


# 3D Complex Split

In [10]:
arr = np.arange(1, 33).reshape(4,4,2)

split0 = np.array_split(arr, 2, axis=0)

for i, part in enumerate(split0):
    print(f"Axis0 Part {i} shape:", part.shape)
    
    split1 = np.array_split(part, 2, axis=1)
    for j, sub in enumerate(split1):
        print(f"  Axis1 Part {j} shape:", sub.shape)

Axis0 Part 0 shape: (2, 4, 2)
  Axis1 Part 0 shape: (2, 2, 2)
  Axis1 Part 1 shape: (2, 2, 2)
Axis0 Part 1 shape: (2, 4, 2)
  Axis1 Part 0 shape: (2, 2, 2)
  Axis1 Part 1 shape: (2, 2, 2)


#  Train / Validation / Test Split

In [11]:
data = np.arange(50)

train_end = int(0.6 * len(data))
val_end = int(0.8 * len(data))

train = data[:train_end]
val = data[train_end:val_end]
test = data[val_end:]

print("Train:", train)
print("Validation:", val)
print("Test:", test)

Train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Validation: [30 31 32 33 34 35 36 37 38 39]
Test: [40 41 42 43 44 45 46 47 48 49]
